/* Generated By:JavaCC: Do not edit this line. BNF2CNF_ParserConstants.java */
/* definición del nombre del analizador */

/* codigo Java utilizado en la descripción del analizador */

package bnf2cnf.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BNF2CNF_ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO = 5;
  /** RegularExpression Id. */
  int NOTERMINAL = 6;
  /** RegularExpression Id. */
  int TERMINAL = 7;
  /** RegularExpression Id. */
  int EQ = 8;
  /** RegularExpression Id. */
  int BAR = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<COMENTARIO>",
    "<NOTERMINAL>",
    "<TERMINAL>",
    "\"::=\"",
    "\"|\"",
    "\";\"",
  };

}
