function r = abbRead(s,r)
% abbRead          Read from ABB RAPID variable into a struct
%                  Communication with robot using PC SDK DLL (ABB.Robotics)
%               
% This function is part of a set of functions intendend to make the use of
% PCSDK from Matlab a little bit easier. For more on PCSDK see:
% http://developercenter.robotstudio.com/pcsdk 
% and information on how Matlab support .NET applications see:
% https://se.mathworks.com/help/matlab/matlab_external/using-net-from-matlab-an-overview.html
%
% see also: abbCom, abbNew
%
% use:
%  r = abbRead(s, r);
%  r = abbRead(s, abbNew(char('T_ROB1','MatlabCom','nMatlabComNum1'), 'num'));
% ------------------------------------------------------------------------------
%  r     A struct as from abbNew,
%  s     A struct for communication, see abbCom
% ------------------------------------------------------------------------------
% ex:   
%   r = abbNew(char('T_ROB1','MatlabCom','pMatlabComOrigo'), 'robtarget');
%   r = struct('RapidName',char('T_ROB1','MatlabCom','pMatlabComOrigo'), 'RapidType','robtarget')
%   abbComStruct = abbCom('Rudolf');
%   r = abbRead(abbComStruct,r);

% Karl S : March 2014, January 2019

if nargin < 2
    r = struct('RapidName', char('Program','Module','VarName'), ...
               'RapidType', '', ...
               'message', [mfilename,': invalid input ',datestr(now)], ...
               'me', '', ...    
               'StringValue', '' );   
    return;
end

% 
if ~isstruct(s) || ~isstruct(r)
    r = struct('RapidName', char('Program','Module','VarName'), ...
               'RapidType', '', ...
               'message', [mfilename,': invalid input, see help.'], ...
               'me', '', ...    
               'StringValue', '' );   
    return;           
end
if ~isfield(s,'ctrl') || ~isfield(s,'connected')
    r.message = [mfilename,': no connection to ABB robot.'];   
    return;           
end
%
if ~isfield(r,'RapidName') || ~ischar(r.RapidName) || (size(r.RapidName,1) < 3)
    r.message = [mfilename,': input r.RapidName is not as expected'];   
    return;           
end

% 
try
    ssVar = NET.createArray('System.String',3);
    ssVar.Set(0, strtrim(r.RapidName(1,:)));
    ssVar.Set(1, strtrim(r.RapidName(2,:)));
    ssVar.Set(2, strtrim(r.RapidName(3,:)));
    rVar = s.ctrl.Rapid.GetRapidData( ssVar );
    disp([mfilename,': Read : ',char(rVar.Name),' from ',s.robot]);
    if ~strcmp(char(rVar.RapidType),r.RapidType)
        disp([' r.RapidType not as in RAPID (',r.RapidType, ...
              '), change it to ',char(rVar.RapidType)]);
    end
    if strcmpi(char(rVar.RapidType),'num')
        r = struct('RapidName', char(char(ssVar(1)),char(ssVar(2)),char(ssVar(3))), ...
                   'RapidType', 'num', ...
                   'Value', rVar.Value.Value,...
                   'message', [mfilename,': read num ',datestr(now)], ...
                   'me', '', ...    
                   'StringValue', char(rVar.StringValue) );   
    elseif strcmpi(char(rVar.RapidType),'bool')
        r = struct('RapidName', char(char(ssVar(1)),char(ssVar(2)),char(ssVar(3))), ...
                   'RapidType', 'bool', ...
                   'Value', logical(rVar.Value.Value),...
                   'message', [mfilename,': read bool ',datestr(now)], ...
                   'me', '', ...    
                   'StringValue', char(rVar.StringValue) );   
    elseif strcmpi(char(rVar.RapidType),'robtarget')
        r = struct('RapidName', char(char(ssVar(1)),char(ssVar(2)),char(ssVar(3))), ...
                   'RapidType', 'robtarget', ...
                   'Trans',struct('X',rVar.Value.Trans.X,...
                                  'Y',rVar.Value.Trans.Y,...
                                  'Z',rVar.Value.Trans.Z),...
                   'Rot',struct('Q1',rVar.Value.Rot.Q1,...
                                'Q2',rVar.Value.Rot.Q2,...
                                'Q3',rVar.Value.Rot.Q3,...
                                'Q4',rVar.Value.Rot.Q4),...
                   'Robconf',struct('Cf1',rVar.Value.Robconf.Cf1,...
                                    'Cf4',rVar.Value.Robconf.Cf4,...
                                    'Cf6',rVar.Value.Robconf.Cf6,...
                                    'Cfx',rVar.Value.Robconf.Cfx),...
                   'Extax',struct('Eax_a',rVar.Value.Extax.Eax_a,...
                                  'Eax_b',rVar.Value.Extax.Eax_b,...
                                  'Eax_c',rVar.Value.Extax.Eax_c,...
                                  'Eax_d',rVar.Value.Extax.Eax_d,...
                                  'Eax_e',rVar.Value.Extax.Eax_e,...
                                  'Eax_f',rVar.Value.Extax.Eax_f),...
                   'message', [mfilename,': read robtarget ',datestr(now)], ...
                   'me', '', ...    
                   'StringValue', char(rVar.StringValue) );   
    elseif strcmpi(char(rVar.RapidType),'tooldata')
        r = struct('RapidName', char(char(ssVar(1)),char(ssVar(2)),char(ssVar(3))), ...
                   'RapidType', 'tooldata', ...
                   'Robhold',rVar.Value.Robhold,...    % (logical)
                   'Tframe', struct('Trans',struct('X',rVar.Value.Tframe.Trans.X, ...
                                                   'Y',rVar.Value.Tframe.Trans.Y, ...
                                                   'Z',rVar.Value.Tframe.Trans.Z),...
                                    'Rot',struct('Q1',rVar.Value.Tframe.Rot.Q1,...
                                                 'Q2',rVar.Value.Tframe.Rot.Q2,...
                                                 'Q3',rVar.Value.Tframe.Rot.Q3,...
                                                 'Q4',rVar.Value.Tframe.Rot.Q4)), ...
                   'Tload', struct('Mass', rVar.Value.Tload.Mass,...
                                   'Ix', rVar.Value.Tload.Ix, ...
                                   'Iy', rVar.Value.Tload.Iy, ...
                                   'Iz', rVar.Value.Tload.Iz, ...
                                   'Cog',struct('X',rVar.Value.Tload.Cog.X,...
                                                'Y',rVar.Value.Tload.Cog.Y,...
                                                'Z',rVar.Value.Tload.Cog.Z),...
                                   'Aom',struct('Q1',rVar.Value.Tload.Aom.Q1,...
                                                'Q2',rVar.Value.Tload.Aom.Q2,...
                                                'Q3',rVar.Value.Tload.Aom.Q3,...
                                                'Q4',rVar.Value.Tload.Aom.Q4)), ...
                   'message', [mfilename,': read tooldata ',datestr(now)], ...
                   'me', '', ...    
                   'StringValue', char(rVar.StringValue) );   
    elseif strcmpi(char(rVar.RapidType),'wobjdata')
        r = struct('RapidName', char(char(ssVar(1)),char(ssVar(2)),char(ssVar(3))), ...
                   'RapidType', 'wobjdata', ...
                   'Robhold',rVar.Value.Robhold,...    % (logical)
                   'Ufprog',rVar.Value.Ufprog, ...  % (logical)
                   'Ufmec',char(rVar.Value.Ufmec), ...       % (string), PC SDK: System String
                   'Uframe', struct('Trans',struct('X',rVar.Value.Uframe.Trans.X,...
                                                   'Y',rVar.Value.Uframe.Trans.Y,...
                                                   'Z',rVar.Value.Uframe.Trans.Z),...
                                    'Rot',struct('Q1',rVar.Value.Uframe.Rot.Q1,...
                                                 'Q2',rVar.Value.Uframe.Rot.Q2,...
                                                 'Q3',rVar.Value.Uframe.Rot.Q3,...
                                                 'Q4',rVar.Value.Uframe.Rot.Q4)), ...
                   'Oframe', struct('Trans',struct('X',rVar.Value.Oframe.Trans.X,...
                                                   'Y',rVar.Value.Oframe.Trans.Y,...
                                                   'Z',rVar.Value.Oframe.Trans.Z),...
                                    'Rot',struct('Q1',rVar.Value.Oframe.Rot.Q1,...
                                                 'Q2',rVar.Value.Oframe.Rot.Q2,...
                                                 'Q3',rVar.Value.Oframe.Rot.Q3,...
                                                 'Q4',rVar.Value.Oframe.Rot.Q4)), ...
                   'message', [mfilename,': read wobjdata ',datestr(now)], ...
                   'me', '', ...    
                   'StringValue', char(rVar.StringValue) );   
    elseif strcmpi(char(rVar.RapidType),'jointtarget')
        r = struct('RapidName', char(char(ssVar(1)),char(ssVar(2)),char(ssVar(3))), ...
                   'RapidType', 'jointtarget', ...
                   'RobAx',struct('Rax_1',rVar.Value.RobAx.Rax_1,...
                                  'Rax_2',rVar.Value.RobAx.Rax_2,...
                                  'Rax_3',rVar.Value.RobAx.Rax_3,...
                                  'Rax_4',rVar.Value.RobAx.Rax_4,...
                                  'Rax_5',rVar.Value.RobAx.Rax_5,...
                                  'Rax_6',rVar.Value.RobAx.Rax_6),...
                   'ExtAx',struct('Eax_a',rVar.Value.ExtAx.Eax_a,...
                                  'Eax_b',rVar.Value.ExtAx.Eax_b,...
                                  'Eax_c',rVar.Value.ExtAx.Eax_c,...
                                  'Eax_d',rVar.Value.ExtAx.Eax_d,...
                                  'Eax_e',rVar.Value.ExtAx.Eax_e,...
                                  'Eax_f',rVar.Value.ExtAx.Eax_f),...
                   'message', [mfilename,': jointtarget struct lest ',datestr(now)], ...
                   'me', '', ...    
                   'StringValue', char(rVar.StringValue) );   
    else
        r = struct('RapidName', char(char(ssVar(1)),char(ssVar(2)),char(ssVar(3))), ...
                   'RapidType', char(rVar.RapidType), ...
                   'message', [mfilename,': not ready for this RapidType '], ...
                   'me', '', ...    
                   'StringValue', '' );   
    end
catch me
    r.message = [mfilename,': error while reading, see field ''me''. ',datestr(now)];
    r.me = me;
end

end
    