function r = abbNew(name,type)
% abbNew           Make a struct with fields as an ABB RAPID variable
%               
% This function is part of a set of functions intendend to make the use of
% PCSDK from Matlab a little bit easier. For more on PCSDK see:
% http://developercenter.robotstudio.com/pcsdk 
% and information on how Matlab support .NET applications see:
% https://se.mathworks.com/help/matlab/matlab_external/using-net-from-matlab-an-overview.html
%
% see also: abbCom, abbEdit, abbString
%
% use:
%  r = abbNew(name);        % only the common fields
%  r = abbNew(name,type);   % also empty fields used for this type
% --------------------------------------------------------------------------
%  r     a struct of fields used by RAPID data variable
%        The common fields are:
%   r.RapidName   Complete name, ex: char('Program','Module','VarName')
%   r.RapidType   The following types may be used here: 
%                 num, bool, robtarget, tooldata, wobjdata, jointtarget 
%   r.StringValue String representing the value
%   r.message     Last message stored
%   r.me          Last error (from catch in Matlab)
%        For   num and bool   
%   r.Value       number (bool 1/0 or true/false)
%        For   robtarget
%   r.Trans       ex: struct('X',0,'Y',0,'Z',0)
%   r.Rot         ex: struct('Q1',0,'Q2',1,'Q3',0,'Q4',0)
%   r.Robconf     ex: struct('Cf1',0,'Cf4',0,'Cf6',0,'Cfx',0)
%   r.Extax       ex: struct('Eax_a',9E9, ... 'Eax_f',9E9)
%        ... and more
%
%   name          corresponds to r.RapidName
%   type          num, bool, robtarget, tooldata, wobjdata, or jointtarget 
% --------------------------------------------------------------------------
% ex:
%  r = abbNew(char('T_ROB1','MatlabCom','pMatlabCom0'), 'robtarget');
%  r = abbNew(char('T_ROB1','MatlabCom','nMatlabComNum1'), 'num');

% Karl S : March 2014, January 2019

if nargin < 1
    name = char('Program','Module','VarName');
end

if nargin < 2
    r = struct('RapidName', name, ...
               'RapidType', 'num', ...
               'message', [mfilename,': make a zero num ',datestr(now)], ...
               'Value', 0, ...
               'me', '', ...    
               'StringValue', '0' );   
else
    if strcmpi(type,'num')
        r = struct('RapidName', name, ...
                   'RapidType', 'num', ...
                   'message', [mfilename,': make a zero num ',datestr(now)], ...
                   'Value', 0, ...
                   'me', '', ...    
                   'StringValue', '0' );   
    elseif strcmpi(type,'bool')
        r = struct('RapidName', name, ...
                   'RapidType', 'bool', ...
                   'message', [mfilename,': make a false bool ',datestr(now)], ...
                   'Value', false, ...
                   'me', '', ...    
                   'StringValue', 'FALSE' );   
    elseif strcmpi(type,'robtarget')
        r = struct('RapidName', name, ...
                   'RapidType', 'robtarget', ...
                   'Trans',struct('X',0,'Y',0,'Z',0),...
                   'Rot',struct('Q1',0,'Q2',1,'Q3',0,'Q4',0),...
                   'Robconf',struct('Cf1',0,'Cf4',0,'Cf6',0,'Cfx',0),...
                   'Extax',struct('Eax_a',9E9,'Eax_b',9E9,'Eax_c',9E9,...
                                  'Eax_d',9E9,'Eax_e',9E9,'Eax_f',9E9),...
                   'message', [mfilename,': make a robtarget ',datestr(now)], ...
                   'me', '', ...    
                   'StringValue', '' );   
    elseif strcmpi(type,'tooldata')
        r = struct('RapidName', name, ...
                   'RapidType', 'tooldata', ...
                   'Robhold',true,...    % (logical)
                   'Tframe', struct('Trans',struct('X',0,'Y',0,'Z',0),...
                                    'Rot',struct('Q1',0,'Q2',1,'Q3',0,'Q4',0)), ...
                   'Tload', struct('Mass', 0.001, ...
                                   'Ix', 0, ...
                                   'Iy', 0, ...
                                   'Iz', 0, ...
                                   'Cog',struct('X',0,'Y',0,'Z',0),...
                                   'Aom',struct('Q1',0,'Q2',1,'Q3',0,'Q4',0)), ...
                   'message', [mfilename,': make a tooldata ',datestr(now)], ...
                   'me', '', ...    
                   'StringValue', '' );   
    elseif strcmpi(type,'wobjdata')
        r = struct('RapidName', name, ...
                   'RapidType', 'wobjdata', ...
                   'Robhold',true,...    % (logical)
                   'Ufprog', false, ...  % (logical)
                   'Ufmec','', ...       % (string), PC SDK: System String
                   'Uframe', struct('Trans',struct('X',0,'Y',0,'Z',0),...
                                    'Rot',struct('Q1',1,'Q2',0,'Q3',0,'Q4',0)), ...
                   'Oframe', struct('Trans',struct('X',0,'Y',0,'Z',0),...
                                    'Rot',struct('Q1',1,'Q2',0,'Q3',0,'Q4',0)), ...
                   'message', [mfilename,': make a wobjdata ',datestr(now)], ...
                   'me', '', ...    
                   'StringValue', '' );   
    elseif strcmpi(type,'jointtarget')
        r = struct('RapidName', name, ...
                   'RapidType', 'jointtarget', ...
                   'RobAx',struct('Rax_1',0,'Rax_2',0,'Rax_3',0,...
                                  'Rax_4',0,'Rax_5',0,'Rax_6',0),...
                   'ExtAx',struct('Eax_a',9E9,'Eax_b',9E9,'Eax_c',9E9,...
                                  'Eax_d',9E9,'Eax_e',9E9,'Eax_f',9E9),...
                   'message', [mfilename,': make a jointtarget ',datestr(now)], ...
                   'me', '', ...    
                   'StringValue', '' );   
    else
        r = struct('RapidName', name, ...
                   'RapidType', '', ...
                   'message', [mfilename,': do not recognize input type ',datestr(now)], ...
                   'me', '', ...    
                   'StringValue', '' );   
    end
    r.StringValue = abbString(r);
end

end
 