--EI-18
SELECT DISTINCT P.despacho
FROM EI.PROFESOR P
WHERE NOT EXISTS 
	(SELECT *
	FROM EI.ASIGNATURA A
	WHERE P.nPr = A.prof);
	
--EI-19
SELECT A.nombre
FROM EI.ALUMNO A
WHERE EXISTS
	(SELECT *
	FROM EI.MATRICULA M
	WHERE (año = 2000 OR año = 2002) AND A.nAl = M.alum)
AND NOT EXISTS
	(SELECT *
	FROM EI.MATRICULA M
	WHERE año = 2001 AND A.nAL = M.alum);
	
--EI-20
SELECT nombre, despacho
FROM EI.PROFESOR P1
WHERE NOT EXISTS
	(SELECT *
	FROM EI.PROFESOR P2
	WHERE P2.despacho = P1.despacho AND P2.nPr <> P1.nPr);

---------------------------------------------------------------------------------------------------
							SESIÓN 4: CONSULTAS ANIDADAS (LA FUNCIÓN EXIST)
---------------------------------------------------------------------------------------------------

--WRC-16
SELECT PI.NombreP
FROM WRC.PILOTO PI
WHERE NOT EXISTS
  (SELECT *
  FROM WRC.RALLY R INNER JOIN WRC.PARTICIPA P USING (codRally)
  WHERE R.nombre = 'Rally de Cataluña' AND P.codPiloto = PI.codpiloto);
  
--WRC-17
SELECT P1.NombreP
FROM WRC.PILOTO P1 INNER JOIN WRC.COCHE C1 ON P1.COCHE=C1.CODCOCHE
WHERE EXISTS
  (SELECT *
  FROM WRC.PILOTO P2 INNER JOIN WRC.COCHE C2 ON P2.COCHE=C2.CODCOCHE
  WHERE P1.PUNTOS > P2.PUNTOS AND C2.CILINDRADA <= C1.CILINDRADA);

--WRC-18
SELECT PI.NombreP
FROM WRC.piloto PI
WHERE EXISTS
	(SELECT *
	FROM WRC.PARTICIPA PA INNER JOIN WRC.RALLY R USING (codRally)
	WHERE R.NOMBRE = 'Rally de Cataluña' AND PA.CODPILOTO = PI.CODPILOTO)
AND NOT EXISTS
	(SELECT *
	FROM WRC.PARTICIPA PA INNER JOIN WRC.RALLY R USING (codRally)
	WHERE R.NOMBRE = 'Rally RAC de Gran Bretaña' AND PA.CODPILOTO = PI.CODPILOTO);
	
--WRC-19
SELECT P1.NombreP
FROM WRC.PILOTO P1
WHERE EXISTS
  (SELECT *
  FROM WRC.CORRE CO INNER JOIN WRC.TRAMO T USING (numeroTramo, codRally)
  WHERE T.DIFICULTAD='A' AND P1.CODPILOTO=CODPILOTO)
AND NOT EXISTS
  (SELECT *
  FROM WRC.CORRE CO INNER JOIN WRC.TRAMO T USING (numeroTramo, codRally)
  WHERE T.TOTALKMS < 30 AND P1.CODPILOTO=CODPILOTO);

--WRC-20
SELECT marca, modelo
FROM WRC.COCHE C1
WHERE
 (SELECT COUNT(*)
 FROM WRC.COCHE C2
 WHERE C1.CILINDRADA > C2.CILINDRADA)>=2;
 
