/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import Persistence.Collaborates;
import Persistence.CollaboratesManager;
import Persistence.Expert;
import Persistence.ExpertManager;
import Persistence.OracleConnection;
import Persistence.Policialcase;
import Persistence.PolicialcaseManager;
import javax.swing.JOptionPane;

/**
 * Contains the view and all the methods to insert a collaboration
 *
 * @author Álvaro Esteban Muñoz
 */
public class InsertCollaboration extends javax.swing.JInternalFrame {

    private final OracleConnection c;
    private final CollaboratesManager cm;
    private final ExpertManager em;
    private final PolicialcaseManager pm;

    /**
     * Creates new form InsertCollabMenu
     *
     * @param c
     */
    public InsertCollaboration(OracleConnection c) {
        initComponents();
        this.c = c;
        cm = new CollaboratesManager(c);
        em = new ExpertManager(c);
        pm = new PolicialcaseManager(c);

        ExpertNameField.setEnabled(false);
        CountryField.setEnabled(false);
        SexField.setEnabled(false);
        SpecialismField.setEnabled(false);
        CaseNameField.setEnabled(false);
        CaseStartDateField.setEnabled(false);
        CaseEndDateField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CodeExpField = new javax.swing.JTextField();
        CodeCaseField = new javax.swing.JTextField();
        StartDateField = new javax.swing.JTextField();
        DescriptionField = new javax.swing.JTextField();
        CodExpLabel = new javax.swing.JLabel();
        CodeCaseLabel = new javax.swing.JLabel();
        StartDateLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        InsertButton = new javax.swing.JButton();
        ExpertNameLabel = new javax.swing.JLabel();
        ExpertNameField = new javax.swing.JTextField();
        CountryField = new javax.swing.JTextField();
        SexField = new javax.swing.JTextField();
        SpecialismField = new javax.swing.JTextField();
        CountryLabel = new javax.swing.JLabel();
        SexLabel = new javax.swing.JLabel();
        SpecialismLabel = new javax.swing.JLabel();
        CaseNameLabel = new javax.swing.JLabel();
        CaseStartDateLabel = new javax.swing.JLabel();
        CaseNameField = new javax.swing.JTextField();
        CaseStartDateField = new javax.swing.JTextField();
        CaseEndDateField = new javax.swing.JTextField();
        CaseEndDateLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        CodExpLabel.setText("Expert Code");

        CodeCaseLabel.setText("Case Code");

        StartDateLabel.setText("Start Date");

        DescriptionLabel.setText("Description");

        InsertButton.setText("Insert");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        ExpertNameLabel.setText("Expert Name");

        CountryLabel.setText("Country");

        SexLabel.setText("Sex");

        SpecialismLabel.setText("Specialism");

        CaseNameLabel.setText("Case Name");

        CaseStartDateLabel.setText("Case Start Date");

        CaseEndDateLabel.setText("Case End Date");

        jButton1.setText("Insert Expert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Insert Case");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CodExpLabel)
                            .addGap(18, 18, 18)
                            .addComponent(CodeExpField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ExpertNameLabel)
                                .addComponent(CountryLabel)
                                .addComponent(SexLabel)
                                .addComponent(SpecialismLabel))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CountryField)
                                .addComponent(ExpertNameField)
                                .addComponent(SexField)
                                .addComponent(SpecialismField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CaseNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CaseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CaseStartDateLabel)
                                    .addComponent(CaseEndDateLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CaseEndDateField)
                                    .addComponent(CaseStartDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StartDateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(StartDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DescriptionLabel)
                                .addGap(18, 18, 18)
                                .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CodeCaseLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CodeCaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InsertButton)
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeExpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodExpLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpertNameLabel)
                    .addComponent(ExpertNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CountryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CountryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SexLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpecialismField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpecialismLabel))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeCaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodeCaseLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CaseNameLabel)
                    .addComponent(CaseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CaseStartDateLabel)
                    .addComponent(CaseStartDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CaseEndDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CaseEndDateLabel))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartDateLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescriptionLabel))
                .addGap(18, 18, 18)
                .addComponent(InsertButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Performs the action of requesting the data to insert the collaboration,
     * but first, it checks if the expert and the case does not exist. If some
     * of them does not exist then it request to the user the data to create
     * either the one that does not exist or both.
     *
     * @param evt
     */
    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed

        String CodeCase, CodeExp;
        CodeExp = CodeExpField.getText();
        CodeCase = CodeCaseField.getText();

        boolean expertExists, caseExsists;
        expertExists = em.expertExists(CodeExp);
        caseExsists = pm.existCase(CodeCase);

        // Expert does not exist but case does
        if (!expertExists && caseExsists) {

            JOptionPane.showMessageDialog(this, "The expert does not exist. Please fill the next fields.");

            ExpertNameField.setEnabled(true);
            CountryField.setEnabled(true);
            SexField.setEnabled(true);
            SpecialismField.setEnabled(true);

            CaseNameField.setEnabled(false);
            CaseStartDateField.setEnabled(false);
            CaseEndDateField.setEnabled(false);
        } else if (expertExists && !caseExsists) {   // Case does not exist but expert does

            JOptionPane.showMessageDialog(this, "The case does not exist. Please fill the next fields.");

            ExpertNameField.setEnabled(false);
            CountryField.setEnabled(false);
            SexField.setEnabled(false);
            SpecialismField.setEnabled(false);

            CaseNameField.setEnabled(true);
            CaseStartDateField.setEnabled(true);
            CaseEndDateField.setEnabled(true);
        } else if (!expertExists && !caseExsists) {  // Neither expert nor case exists

            JOptionPane.showMessageDialog(this, "The expert does not exist. Please fill the next fields.");
            JOptionPane.showMessageDialog(this, "The case does not exist. Please fill the next fields.");

            ExpertNameField.setEnabled(true);
            CountryField.setEnabled(true);
            SexField.setEnabled(true);
            SpecialismField.setEnabled(true);

            CaseNameField.setEnabled(true);
            CaseStartDateField.setEnabled(true);
            CaseEndDateField.setEnabled(true);
        }

        if (expertExists && caseExsists) {
            insertCollab(CodeExp, CodeCase);
        }
    }//GEN-LAST:event_InsertButtonActionPerformed

    /**
     * Calls the insertExp function
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        insertExp(CodeExpField.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Calls the insertCase function
     *
     * @param evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        insertCase(CodeCaseField.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Insert the collaboration on the DB
     */
    private void insertCollab(String CodeExp, String CodeCase) {

        boolean succed = false;
        String StartDate, Desc;

        StartDate = StartDateField.getText();
        Desc = DescriptionField.getText();
        Collaborates col = new Collaborates();

        col.setCodExperto(CodeExp);
        col.setCodcaso(CodeCase);
        col.setFecha(StartDate);
        col.setDescripcionColaboracion(Desc);

        c.startTransaction();
        succed = cm.insertCollaboration(col);

        if (succed) {
            JOptionPane.showMessageDialog(this, "Collaborator inserted succesfully.");
            c.endTransaccionCommit();
        } else {
            c.endfTransaccionRollback();
        }
    }

    /**
     * Insert the exp on the DB
     *
     * @param CodeExp
     */
    private void insertExp(String CodeExp) {

        boolean succed = false;
        String Name, Country, Sex, Specialism;

        Name = ExpertNameField.getText();
        Country = CountryField.getText();
        Sex = SexField.getText();
        Specialism = SpecialismField.getText();
        Expert exp = new Expert(CodeExp, Name, Country, Sex, Specialism);

        c.startTransaction();
        succed = em.insertExpert(exp);

        if (succed) {
            JOptionPane.showMessageDialog(this, "Expert inserted succesfully.");
            c.endTransaccionCommit();
        } else {
            c.endfTransaccionRollback();
        }

    }

    /**
     * Insert the case on the DB
     *
     * @param CodeCase
     */
    private void insertCase(String CodeCase) {

        boolean succed = false;
        String Name, StartDate, EndDate;

        Name = CaseNameField.getText();
        StartDate = CaseStartDateField.getText();
        EndDate = CaseEndDateField.getText();
        Policialcase pcas = new Policialcase(CodeCase, Name, StartDate, EndDate);

        c.startTransaction();
        succed = pm.insertCase(pcas);

        if (succed) {
            JOptionPane.showMessageDialog(this, "Case inserted succesfully.");
            c.endTransaccionCommit();
        } else {
            c.endfTransaccionRollback();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CaseEndDateField;
    private javax.swing.JLabel CaseEndDateLabel;
    private javax.swing.JTextField CaseNameField;
    private javax.swing.JLabel CaseNameLabel;
    private javax.swing.JTextField CaseStartDateField;
    private javax.swing.JLabel CaseStartDateLabel;
    private javax.swing.JLabel CodExpLabel;
    private javax.swing.JTextField CodeCaseField;
    private javax.swing.JLabel CodeCaseLabel;
    private javax.swing.JTextField CodeExpField;
    private javax.swing.JTextField CountryField;
    private javax.swing.JLabel CountryLabel;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JTextField ExpertNameField;
    private javax.swing.JLabel ExpertNameLabel;
    private javax.swing.JButton InsertButton;
    private javax.swing.JTextField SexField;
    private javax.swing.JLabel SexLabel;
    private javax.swing.JTextField SpecialismField;
    private javax.swing.JLabel SpecialismLabel;
    private javax.swing.JTextField StartDateField;
    private javax.swing.JLabel StartDateLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
