/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pcd_práctica9;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class Frame extends java.awt.Frame {

    // Constantes
    private static final int ANCHO = 500;
    private static final int ALTO = 720;

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Creamos el frame de la aplicación
        Frame f = new Frame();
        f.setTitle("Práctica 9 - Álvaro Esteban Muñoz: KeyCracker");
        f.setSize(ANCHO, ALTO);
        f.setResizable(false);
        f.setLocationRelativeTo(null);
        f.setVisible(true);

        Canvas c = new Canvas();

        f.add(c);   // Añadimos el canvas al frame
        c.setVisible(true);
        
        int nHilos;
        String clave;
        Scanner scan = new Scanner(System.in);
        
        //****************** PIDE LOS DATOS POR PANTALLA *********************//
        System.out.print("Introduzca el número de hilos para la thread pool (más de 1 y menos de 10): ");
        do {
            
            nHilos = scan.nextInt();
            
            if (nHilos < 1 || nHilos > 10 ) {
                System.out.print("Número de hilos no valido. Introduzca de nuevo:");
            }
        } while(nHilos < 1 || nHilos > 10 );
        
        System.out.print("Introduzca la clave que desea crackear (6 dígitos del 0 al 9):");
        do {
            
            clave = scan.nextLine();
            
            if (clave.toCharArray().length != 6) {
                System.out.print("La clave debe ser de 6 dígitos, introduzca otra vez: ");
            }
        } while(clave.toCharArray().length != 6);
        //********************************************************************//
        
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            //String clave = "654321";
            byte[] hash = md.digest(clave.getBytes());

            // Transformamos los bytes de dos en dos a carácter hexadecimal
            StringBuilder hex = new StringBuilder();
            for (int i = 0; i < hash.length; i++) {

                if ((0xff & hash[i]) < 0x10) {
                    hex.append("0").append(Integer.toHexString((0xFF & hash[i])).toUpperCase());
                } else {
                    hex.append(Integer.toHexString(0xFF & hash[i]).toUpperCase());
                }
            }
            System.out.println(hex.toString());

            Supervisor s = new Supervisor(nHilos, hex.toString(), c);

            s.start();  // Lanzamos al hilo supervisor
            s.join();   // Esperamos a que acabe
        } catch (NoSuchAlgorithmException | InterruptedException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
