/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import Persistence.CollaboratesManager;
import Persistence.OracleConnection;
import javax.swing.JOptionPane;

/**
 * Contains the view and the methods to delete a collaboration
 *
 * @author Álvaro Esteban Muñoz
 */
public class DeleteCollaboration extends javax.swing.JInternalFrame {

    private final OracleConnection c;   // Conection to the DB
    private final CollaboratesManager cm;   // Collaboration manager to the DB

    /**
     * Creates new form DeleteCollabMenu
     */
    public DeleteCollaboration(OracleConnection c) {
        initComponents();
        this.c = c;
        cm = new CollaboratesManager(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CodeCaseField = new javax.swing.JTextField();
        CodeExpField = new javax.swing.JTextField();
        CodeCaseLabel = new javax.swing.JLabel();
        CodeExpLabel = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();

        CodeCaseLabel.setText("Case Code");

        CodeExpLabel.setText("Expert Code");

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CodeCaseLabel)
                    .addComponent(CodeExpLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CodeCaseField)
                    .addComponent(CodeExpField)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(DeleteButton)
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeCaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodeCaseLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeExpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodeExpLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(DeleteButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Removes the collaboration from the database
     *
     * @param evt
     */
    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed

        boolean succed = false;
        String ce, cc;
        ce = CodeExpField.getText();
        cc = CodeCaseField.getText();

        succed = cm.deleteCollaboration(ce, cc);

        if (succed) {
            JOptionPane.showMessageDialog(this, "Collaborator deleted succesfully.");
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodeCaseField;
    private javax.swing.JLabel CodeCaseLabel;
    private javax.swing.JTextField CodeExpField;
    private javax.swing.JLabel CodeExpLabel;
    private javax.swing.JButton DeleteButton;
    // End of variables declaration//GEN-END:variables
}
