/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import Persistence.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * This is the Graphical User Interface of the application, all the others
 * views are called within this class.
 * @author Álvaro Esteban Muñoz
 */
public class GUI extends javax.swing.JFrame {

    static OracleConnection co = null;  // Here we store the connection to the DB
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        DesktopPane = new javax.swing.JDesktopPane();
        MenuBar = new javax.swing.JMenuBar();
        Conecction_Menu = new javax.swing.JMenu();
        Connect_Submenu = new javax.swing.JMenuItem();
        Disconnect_Submenu = new javax.swing.JMenuItem();
        Experts_Menu = new javax.swing.JMenu();
        ExpertsManagement_Submenu = new javax.swing.JMenuItem();
        NewExpert_Submenu = new javax.swing.JMenuItem();
        Cases_Menu = new javax.swing.JMenu();
        ManageCases_Submenu = new javax.swing.JMenuItem();
        Collaborations_Menu = new javax.swing.JMenu();
        Insert_Submenu = new javax.swing.JMenuItem();
        Update_Submenu = new javax.swing.JMenuItem();
        Delete_Submenu = new javax.swing.JMenuItem();
        ManageByExpert_Submenu = new javax.swing.JMenuItem();
        ManageByCase_Submenu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sildavia Police Control");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1680, 1050));
        setSize(new java.awt.Dimension(1680, 1050));

        DesktopPane.setPreferredSize(new java.awt.Dimension(0, 362));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1680, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );

        MenuBar.setPreferredSize(new java.awt.Dimension(250, 20));

        Conecction_Menu.setText("Connection");

        Connect_Submenu.setText("Connect");
        Connect_Submenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Connect_SubmenuActionPerformed(evt);
            }
        });
        Conecction_Menu.add(Connect_Submenu);

        Disconnect_Submenu.setText("Disconnect");
        Disconnect_Submenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Disconnect_SubmenuActionPerformed(evt);
            }
        });
        Conecction_Menu.add(Disconnect_Submenu);

        MenuBar.add(Conecction_Menu);

        Experts_Menu.setText("Experts");

        ExpertsManagement_Submenu.setText("Experts Management");
        ExpertsManagement_Submenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpertsManagement_SubmenuActionPerformed(evt);
            }
        });
        Experts_Menu.add(ExpertsManagement_Submenu);

        NewExpert_Submenu.setText("New Expert");
        NewExpert_Submenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewExpert_SubmenuActionPerformed(evt);
            }
        });
        Experts_Menu.add(NewExpert_Submenu);

        MenuBar.add(Experts_Menu);

        Cases_Menu.setText("Cases");

        ManageCases_Submenu.setText("Cases Management");
        ManageCases_Submenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCases_SubmenuActionPerformed(evt);
            }
        });
        Cases_Menu.add(ManageCases_Submenu);

        MenuBar.add(Cases_Menu);

        Collaborations_Menu.setText("Collaborations");

        Insert_Submenu.setText("Insert");
        Insert_Submenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_SubmenuActionPerformed(evt);
            }
        });
        Collaborations_Menu.add(Insert_Submenu);

        Update_Submenu.setText("Update");
        Update_Submenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_SubmenuActionPerformed(evt);
            }
        });
        Collaborations_Menu.add(Update_Submenu);

        Delete_Submenu.setText("Delete");
        Delete_Submenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_SubmenuActionPerformed(evt);
            }
        });
        Collaborations_Menu.add(Delete_Submenu);

        ManageByExpert_Submenu.setText("Manage by Expert");
        ManageByExpert_Submenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageByExpert_SubmenuActionPerformed(evt);
            }
        });
        Collaborations_Menu.add(ManageByExpert_Submenu);

        ManageByCase_Submenu.setText("Manage by Case");
        ManageByCase_Submenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageByCase_SubmenuActionPerformed(evt);
            }
        });
        Collaborations_Menu.add(ManageByCase_Submenu);

        MenuBar.add(Collaborations_Menu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Initializes the conecction to the DB.
     * @param evt 
     */
    private void Connect_SubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Connect_SubmenuActionPerformed
        
        try {
            co = new OracleConnection();
            JOptionPane.showMessageDialog(null ,"Connected succesfully");
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null ,"Connetion error: " + e.getMessage());
        }    
	catch (Exception e) {
            JOptionPane.showMessageDialog(null ,"Error: " + e.getMessage());
        }
    }//GEN-LAST:event_Connect_SubmenuActionPerformed

    /**
     * Disconects from the DB
     * @param evt 
     */
    private void Disconnect_SubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Disconnect_SubmenuActionPerformed
        
        try {
            co.disconnect();
            JOptionPane.showMessageDialog(null, "Disconnected succesfully");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null ,"Connetion error: " + ex.getMessage());
        }
    }//GEN-LAST:event_Disconnect_SubmenuActionPerformed

    /**
     * Launches the view to the ManageByCase view
     * @param evt 
     */
    private void ManageByCase_SubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageByCase_SubmenuActionPerformed
        ManageByCase collman_menu = new ManageByCase(co);
        DesktopPane.add(collman_menu);
        collman_menu.setClosable(true);
        collman_menu.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        collman_menu.setVisible(true);
    }//GEN-LAST:event_ManageByCase_SubmenuActionPerformed

    /**
     * Launches the view to the ExpertsManagement view
     * @param evt 
     */
    private void ExpertsManagement_SubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpertsManagement_SubmenuActionPerformed
        ExpertsManagement expman_menu = new ExpertsManagement(co);
        DesktopPane.add(expman_menu);
        expman_menu.setClosable(true);
        expman_menu.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        expman_menu.setVisible(true);
    }//GEN-LAST:event_ExpertsManagement_SubmenuActionPerformed

    /**
     * Launches the view to the NewCase view
     * @param evt 
     */
    private void ManageCases_SubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCases_SubmenuActionPerformed
        NewCase casesFrame = new NewCase(co);
        casesFrame.setLocationRelativeTo(null);
        casesFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        casesFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                co.endfTransaccionRollback();
            }
        });

        casesFrame.setVisible(true);
    }//GEN-LAST:event_ManageCases_SubmenuActionPerformed

    /**
     * Launches the view to the NewExpert view
     * @param evt 
     */
    private void NewExpert_SubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewExpert_SubmenuActionPerformed
        NewExpert expertsFrame = new NewExpert(co);
        expertsFrame.setLocationRelativeTo(null);
        expertsFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        expertsFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                co.endfTransaccionRollback();
            }
        });

        expertsFrame.setVisible(true);
    }//GEN-LAST:event_NewExpert_SubmenuActionPerformed

    /**
     * Launches the view to the InsertCollaboration view
     * @param evt 
     */
    private void Insert_SubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_SubmenuActionPerformed
        InsertCollaboration icm = new InsertCollaboration(co);
        DesktopPane.add(icm);
        icm.setClosable(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        icm.setVisible(true);
    }//GEN-LAST:event_Insert_SubmenuActionPerformed

    /**
     * Launches the view to the DeleteCollaboration view
     * @param evt 
     */
    private void Delete_SubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_SubmenuActionPerformed
        DeleteCollaboration dcm = new DeleteCollaboration(co);
        DesktopPane.add(dcm);
        dcm.setClosable(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dcm.setVisible(true);
    }//GEN-LAST:event_Delete_SubmenuActionPerformed

    /**
     * Launches the view to the ManageByExpert view
     * @param evt 
     */
    private void ManageByExpert_SubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageByExpert_SubmenuActionPerformed
        ManageByExpert ManageFrame = new ManageByExpert(co);
        ManageFrame.setTitle("Manage Collaborations");
        ManageFrame.setLocationRelativeTo(null);
        ManageFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ManageFrame.setVisible(true);
    }//GEN-LAST:event_ManageByExpert_SubmenuActionPerformed

    /**
     * Launches the view to the UpdateCollaboration view
     * @param evt 
     */
    private void Update_SubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_SubmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_SubmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // From now on, I control the GUI
        GUI frame = new GUI();
        frame.setSize(600, 400);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cases_Menu;
    private javax.swing.JMenu Collaborations_Menu;
    private javax.swing.JMenu Conecction_Menu;
    private javax.swing.JMenuItem Connect_Submenu;
    private javax.swing.JMenuItem Delete_Submenu;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuItem Disconnect_Submenu;
    private javax.swing.JMenuItem ExpertsManagement_Submenu;
    private javax.swing.JMenu Experts_Menu;
    private javax.swing.JMenuItem Insert_Submenu;
    private javax.swing.JMenuItem ManageByCase_Submenu;
    private javax.swing.JMenuItem ManageByExpert_Submenu;
    private javax.swing.JMenuItem ManageCases_Submenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem NewExpert_Submenu;
    private javax.swing.JMenuItem Update_Submenu;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
